# Generated by Django 4.1.3 on 2022-12-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nflscoreapp', '0004_alter_jogador_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='resultado',
            field=models.FloatField(blank=True),
        ),
    ]
